### PR TITLE
Added rJava info

### PR DESCRIPTION
**Pull request by DeniseSl22**
Installing rJava was not straightforward, so I added some more hints on that @egonw

### CODE REVIEW

**Comment by egonw** [comment]
@DeniseSl22, I'm going to need some more explanation about what the `install.R` and `runtime.txt` files are.

**Comment by DeniseSl22** [comment]
@egonw , those other files were made by you (at least the commits are), I'm not sure what that's about. I will try to make a fresh branch which is in line with the current main, and perform my PR again (without the other files).

**Comment by egonw** [comment]
Oh! Sorry, I did not see that. And bad me for writing lazy commit messages :(

**Comment by egonw** [comment]
@tabbassidaloii, can you please review this patch?

**Review by tabbassidaloii — APPROVED** [review]

**Comment by tabbassidaloii** [comment]
> @tabbassidaloii, can you please review this patch?

@egonw I would only merge README.md. How the package should be installed is already in the README file and the other file doesn't make sense to me

**Pull request closed without merging**
